---
- name: Pull docker image of calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull sanandansharma/calculator-devops
    - name: running container
      shell: docker run -it -d sanandansharma/calculator-devops/bin/bash
